Switches CODEOWNERS to telemetry-team
honeycombio/honeyaws pull request #125
Opened 2021-06-28 21:35 UTC by bdarfler

2021-06-28 21:54 UTC, MikeGoldsmith approved these changes

2021-06-28 21:55 UTC, MikeGoldsmith requested changes

2021-06-28 21:55 UTC, MikeGoldsmith commented on .github/CODEOWNERS
> +* @honeycombio/telemetry-team @nathanleclaire
Nathan is no longer with Honeycomb.

```suggestion
* @honeycombio/telemetry-team 
```

2021-06-29 19:10 UTC, robbkidd approved these changes

2021-06-29 19:20 UTC, MikeGoldsmith approved these changes

2021-06-29 19:27 UTC, merged